title: Glow in the Dark Wall Clock
description: A step-by-step guide to making a glow in the dark wall clock
author: sbnbob
baseurl: ""
url: ""
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    value:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

